import { IProduct, ICategory } from '@/types';

export const MOCK_CATEGORIES: ICategory[] = [
  {
    _id: 'cat-1',
    name: 'Pipes & Tubes',
    slug: 'pipes-tubes',
    description: 'High-tensile ERW, CR, HR, and Galvanized steel pipes for structural, plumbing, and industrial applications.',
    iconName: 'Pipette',
    productCount: 4,
  },
  {
    _id: 'cat-2',
    name: 'Coils & Slit Strips',
    slug: 'coils-strips',
    description: 'Precision-slitted HRPO, GP, CRCA, and CRFH steel coils tailored for automotives, engineering, and fabrication.',
    iconName: 'Disc',
    productCount: 4,
  },
  {
    _id: 'cat-3',
    name: 'Scaffolding Systems',
    slug: 'scaffolding',
    description: 'Heavy-duty modular Cuplock scaffolding standards, ledgers, and props for infrastructure and high-rise construction.',
    iconName: 'Building2',
    productCount: 1,
  },
  {
    _id: 'cat-4',
    name: 'M.S. Billets & Raw Steel',
    slug: 'billets',
    description: 'High-purity continuously cast M.S. Billets and Sponge Iron manufactured in integrated induction furnace kilns.',
    iconName: 'Layers',
    productCount: 1,
  },
];

export const MOCK_PRODUCTS: IProduct[] = [
  // 1. PIPES & TUBES
  {
    _id: 'prod-hr-pipes',
    name: 'HR Pipes and Tubes',
    slug: 'hr-pipes-and-tubes',
    category: {
      _id: 'cat-1',
      name: 'Pipes & Tubes',
      slug: 'pipes-tubes',
    },
    brand: 'Hariom Veer',
    shortDescription: 'Heavy-duty Hot Rolled ERW steel pipes engineered for high load-bearing structural & industrial frameworks.',
    description: 'Hariom Veer HR Pipes & Tubes are manufactured using premium hot-rolled steel coils via High-Frequency Induction Welding (HFIW). Engineered for maximum structural integrity, yield strength, and uniform wall thickness in heavy infrastructure.',
    applications: ['Solar Mounting Structures', 'Industrial Sheds', 'Agricultural Equipment', 'Automotive Chassis', 'General Engineering'],
    specifications: [
      { name: 'Standard Compliance', value: 'IS 1161 / IS 1239 / IS 4923' },
      { name: 'Outer Diameter (OD)', value: '15mm - 219mm (1/2" to 8")' },
      { name: 'Thickness Range', value: '1.2mm - 8.0mm' },
      { name: 'Yield Strength', value: '≥ 240 MPa to 310 MPa' },
      { name: 'Tensile Strength', value: '330 MPa - 510 MPa' },
      { name: 'Shape Profile', value: 'Circular, Square (SHS), Rectangular (RHS)' },
    ],
    availableSizes: ['15NB to 200NB', '20x20mm to 150x150mm SHS', '40x20mm to 200x100mm RHS'],
    standards: ['IS 1161', 'IS 1239', 'IS 4923', 'ASTM A500'],
    finishes: ['Black Bare Finish', 'Red Oxide Primer', 'Varnished Edge'],
    images: ['/images/products/hr-pipes.webp'],
    featured: true,
    isPublished: true,
    viewsCount: 1420,
    createdAt: '2026-01-15T00:00:00.000Z',
    updatedAt: '2026-03-01T00:00:00.000Z',
  },
  {
    _id: 'prod-cr-pipes',
    name: 'CR Pipes',
    slug: 'cr-pipes',
    category: {
      _id: 'cat-1',
      name: 'Pipes & Tubes',
      slug: 'pipes-tubes',
    },
    brand: 'Dura Edge',
    shortDescription: 'Precision Cold Rolled steel pipes featuring ultra-smooth surface finish and high dimensional accuracy.',
    description: 'Dura Edge CR Pipes are produced from cold-rolled steel coils with strict dimensional tolerances and a pristine surface quality ideal for powder coating, chrome plating, and precision furniture manufacturing.',
    applications: ['Steel Furniture & Ergonomic Chairs', 'Automotive Exhausts & Shock Absorbers', 'Gym Equipment', 'Electrical Conduits', 'Retail Display Systems'],
    specifications: [
      { name: 'Standard Compliance', value: 'IS 3074 / IS 13238' },
      { name: 'Outer Diameter (OD)', value: '12.7mm - 76.2mm' },
      { name: 'Thickness Range', value: '0.6mm - 3.0mm' },
      { name: 'Surface Finish', value: 'CR Bright Annealed Finish' },
      { name: 'Tolerance', value: '±0.05mm Precision' },
      { name: 'Formability', value: 'Excellent Bending & Flaring' },
    ],
    availableSizes: ['1/2" to 3" Round', '12x12mm to 60x60mm Square'],
    standards: ['IS 3074', 'IS 13238', 'DIN 2394'],
    finishes: ['CR Bright Finish', 'Oiled Finish', 'Pickled & Oiled'],
    images: ['/images/products/cr-pipes.webp'],
    featured: true,
    isPublished: true,
    viewsCount: 1180,
    createdAt: '2026-01-18T00:00:00.000Z',
    updatedAt: '2026-03-02T00:00:00.000Z',
  },
  {
    _id: 'prod-gi-pipes',
    name: 'GI Pipes (Hot Dipped Galvanized)',
    slug: 'gi-pipes',
    category: {
      _id: 'cat-1',
      name: 'Pipes & Tubes',
      slug: 'pipes-tubes',
    },
    brand: 'Zincon',
    shortDescription: 'Corrosion-resistant Hot Dipped Galvanized pipes engineered for harsh outdoor environments & water transport.',
    description: 'Zincon GI Pipes undergo total immersion in molten zinc (99.99% purity) at 450°C at our state-of-the-art Perundurai galvanizing plant, achieving uniform zinc coating (> 360 g/m²) for multi-decade rust protection.',
    applications: ['Water Supply & Plumbing', 'Firefighting Pipeline Systems', 'Agricultural Borewells & Sprinklers', 'Highway Fencing & Guardrails', 'Greenhouse Frames'],
    specifications: [
      { name: 'Standard Compliance', value: 'IS 1239 (Part-1) / IS 4736' },
      { name: 'Zinc Coating Density', value: '≥ 360 g/m² (55 microns thickness)' },
      { name: 'Hydrostatic Test Pressure', value: 'Tested up to 5 MPa (50 bar)' },
      { name: 'Class Grades', value: 'Light (A-Class), Medium (B-Class), Heavy (C-Class)' },
      { name: 'Thread Protection', value: 'BSP Threaded with Protective Caps' },
    ],
    availableSizes: ['15NB to 150NB (1/2" to 6")', 'Light, Medium & Heavy Series'],
    standards: ['IS 1239', 'IS 4736', 'BS 1387'],
    finishes: ['Hot Dipped Galvanized', 'Passivated Zinc Coating'],
    images: ['/images/products/gi-pipes.webp'],
    featured: true,
    isPublished: true,
    viewsCount: 2150,
    createdAt: '2026-01-10T00:00:00.000Z',
    updatedAt: '2026-03-15T00:00:00.000Z',
  },
  {
    _id: 'prod-gp-pipes',
    name: 'GP Pipes (Pre Galvanized)',
    slug: 'gp-pipes',
    category: {
      _id: 'cat-1',
      name: 'Pipes & Tubes',
      slug: 'pipes-tubes',
    },
    brand: 'Hariom Pipes',
    shortDescription: 'Pre-galvanized ERW steel pipes providing smooth zinc aesthetics and light-to-medium outdoor protection.',
    description: 'Manufactured from pre-galvanized steel sheets, GP Pipes feature a clean metallic sheen and protective zinc layer suitable for architectural handrails, fencing, and light structural framing.',
    applications: ['Architectural Handrails & Gates', 'Bus Shelters & Canopy Frames', 'Solar Panel Racking', 'Scaffolding Guard Tubes'],
    specifications: [
      { name: 'Standard Compliance', value: 'IS 277 / IS 3601' },
      { name: 'Zinc Coating', value: '120 g/m² - 180 g/m²' },
      { name: 'Thickness Range', value: '1.0mm - 3.0mm' },
      { name: 'Weld Seam Protection', value: 'Inline Zinc Spray Metallization' },
    ],
    availableSizes: ['1/2" to 4" Round & Square'],
    standards: ['IS 277', 'IS 3601'],
    finishes: ['Pre-Galvanized Spangle Finish', 'Inline Metalized Seam'],
    images: ['/images/products/gp-pipes.webp'],
    featured: false,
    isPublished: true,
    viewsCount: 940,
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-03-10T00:00:00.000Z',
  },

  // 2. SLIT COILS
  {
    _id: 'prod-hrpo-coils',
    name: 'HRPO Slit Coils',
    slug: 'hrpo-slit-coils',
    category: {
      _id: 'cat-2',
      name: 'Coils & Slit Strips',
      slug: 'coils-strips',
    },
    brand: 'Hariom Coils',
    shortDescription: 'Hot Rolled Pickled & Oiled steel slit coils free of oxide scale for clean presswork and stamping.',
    description: 'HRPO Slit Coils pass through acid pickling lines to remove heavy oxide scales, followed by rust-inhibiting oiling. Perfect for deep drawing, laser cutting, and tube mill feeding.',
    applications: ['Automotive Stamped Components', 'Heavy Machinery Panels', 'Tube Mill Feedstock', 'Cable Tray Manufacturing'],
    specifications: [
      { name: 'Thickness Range', value: '1.6mm - 6.0mm' },
      { name: 'Slitting Width', value: '25mm - 1250mm' },
      { name: 'Width Tolerance', value: '±0.12mm' },
      { name: 'Surface Quality', value: 'Scale-Free Pickled & Oiled' },
    ],
    availableSizes: ['Custom slit widths from 25mm to 1250mm'],
    standards: ['IS 1079', 'IS 2062', 'ASTM A1011'],
    finishes: ['Pickled & Oiled (PO)'],
    images: ['/images/products/hrpo-coils.webp'],
    featured: true,
    isPublished: true,
    viewsCount: 890,
    createdAt: '2026-02-05T00:00:00.000Z',
    updatedAt: '2026-03-08T00:00:00.000Z',
  },
  {
    _id: 'prod-gp-coils',
    name: 'GP Slit Coils',
    slug: 'gp-slit-coils',
    category: {
      _id: 'cat-2',
      name: 'Coils & Slit Strips',
      slug: 'coils-strips',
    },
    brand: 'Zincon Coils',
    shortDescription: 'Galvanized Plain slit strips offering superior edge quality and uniform zinc coating.',
    description: 'Zincon GP Slit Coils provide exceptional corrosion resistance and formability, processed on high-speed CNC slitting lines with minimal burr.',
    applications: ['HVAC Ducting & Flanges', 'Roofing Profile Forming', 'Electrical Enclosures', 'Cable Management Systems'],
    specifications: [
      { name: 'Thickness Range', value: '0.4mm - 2.5mm' },
      { name: 'Zinc Coating', value: '90 g/m² - 275 g/m² (Zero Spangle / Regular)' },
      { name: 'Width Tolerance', value: '±0.10mm' },
    ],
    availableSizes: ['Slit widths 20mm - 1200mm'],
    standards: ['IS 277', 'ASTM A653'],
    finishes: ['Zero Spangle', 'Regular Spangle', 'Chromated'],
    images: ['/images/products/gp-coils.webp'],
    featured: false,
    isPublished: true,
    viewsCount: 760,
    createdAt: '2026-02-08T00:00:00.000Z',
    updatedAt: '2026-03-09T00:00:00.000Z',
  },
  {
    _id: 'prod-crca-coils',
    name: 'CRCA Slit Coils',
    slug: 'crca-slit-coils',
    category: {
      _id: 'cat-2',
      name: 'Coils & Slit Strips',
      slug: 'coils-strips',
    },
    brand: 'Dura Edge Coils',
    shortDescription: 'Cold Rolled Close Annealed steel coils engineered for high-precision forming and paint adhesion.',
    description: 'Dura Edge CRCA Slit Coils feature controlled grain structure, excellent drawability, and flat shape profile for home appliances and office furniture.',
    applications: ['Refrigerators & Washing Machines', 'Control Panels & Switchgears', 'Precision Tubing Feedstock'],
    specifications: [
      { name: 'Thickness Range', value: '0.40mm - 2.50mm' },
      { name: 'Temper / Grade', value: 'D, DD, EDD Grades (Deep Drawing)' },
      { name: 'Surface Finish', value: 'Matte / Bright Finish' },
    ],
    availableSizes: ['Custom widths 15mm - 1250mm'],
    standards: ['IS 513', 'DIN 1623'],
    finishes: ['Oiled Matte Finish', 'Dry Annealed'],
    images: ['/images/products/crca-coils.webp'],
    featured: true,
    isPublished: true,
    viewsCount: 1030,
    createdAt: '2026-02-12T00:00:00.000Z',
    updatedAt: '2026-03-12T00:00:00.000Z',
  },
  {
    _id: 'prod-crfh-coils',
    name: 'CRFH Slit Coils',
    slug: 'crfh-slit-coils',
    category: {
      _id: 'cat-2',
      name: 'Coils & Slit Strips',
      slug: 'coils-strips',
    },
    brand: 'Hariom Coils',
    shortDescription: 'Cold Rolled Full Hard slit coils with un-annealed high hardness for galvanizing & re-rolling.',
    description: 'CRFH Slit Coils offer high yield strength in un-annealed condition, primarily supplied as raw feedstock for continuous galvanizing lines and high-tensile strapping.',
    applications: ['Continuous Galvanizing Line (CGL) Feedstock', 'Steel Strapping & Packaging', 'Drum & Barrel Hoops'],
    specifications: [
      { name: 'Thickness Range', value: '0.30mm - 2.0mm' },
      { name: 'Hardness', value: 'HRB ≥ 85 (Full Hard)' },
      { name: 'Tensile Strength', value: '≥ 550 MPa' },
    ],
    availableSizes: ['Slit widths 20mm - 1000mm'],
    standards: ['IS 513 (Part-1)', 'ASTM A109'],
    finishes: ['Full Hard Unannealed', 'Lightly Oiled'],
    images: ['/images/products/crfh-coils.webp'],
    featured: false,
    isPublished: true,
    viewsCount: 610,
    createdAt: '2026-02-15T00:00:00.000Z',
    updatedAt: '2026-03-05T00:00:00.000Z',
  },

  // 3. STRUCTURAL & SCAFFOLDING
  {
    _id: 'prod-scaffolding',
    name: 'Scaffolding Systems',
    slug: 'scaffolding-systems',
    category: {
      _id: 'cat-3',
      name: 'Scaffolding Systems',
      slug: 'scaffolding',
    },
    brand: 'Build Master',
    shortDescription: 'Heavy-duty modular Cuplock scaffolding standards, ledgers, and adjustable telescopic props.',
    description: 'Build Master Scaffolding Systems are engineered from high-grade structural steel tubes for maximum load capacity and safety on multi-story building projects, bridges, and industrial plants.',
    applications: ['Commercial High-Rise Construction', 'Bridge & Flyover Shuttering', 'Industrial Maintenance Platforms', 'Concrete Slab Formwork'],
    specifications: [
      { name: 'System Types', value: 'Cuplock Vertical Standards, Horizontal Ledgers, Telescopic Props' },
      { name: 'Tube Material', value: 'High-Tensile ERW Steel Tube (48.3mm OD x 3.2mm / 4.0mm)' },
      { name: 'Locking Mechanism', value: 'Malleable Cast Iron Top & Bottom Cups' },
      { name: 'Finish Options', value: 'Painted Red Oxide / Hot Dipped Galvanized' },
    ],
    availableSizes: ['Standards: 1.0m to 3.0m', 'Ledgers: 0.9m to 2.5m', 'Props: 2m-3.5m, 3m-4.5m'],
    standards: ['IS 2750', 'BS 1139', 'EN 12810'],
    finishes: ['Hot Dipped Galvanized', 'Dip Painted Red/Yellow'],
    images: ['/images/products/scaffolding.webp'],
    featured: true,
    isPublished: true,
    viewsCount: 1680,
    createdAt: '2026-01-20T00:00:00.000Z',
    updatedAt: '2026-03-14T00:00:00.000Z',
  },

  // 4. M.S. BILLETS & RAW STEEL
  {
    _id: 'prod-ms-billets',
    name: 'M.S. Billets',
    slug: 'ms-billets',
    category: {
      _id: 'cat-4',
      name: 'M.S. Billets & Raw Steel',
      slug: 'billets',
    },
    brand: 'Hariom Steel',
    shortDescription: 'High-purity Continuously Cast Mild Steel Billets for re-rolling into TMT bars, structural angles & wire rods.',
    description: 'Produced at Unit I (Mahabubnagar) & Unit II (Ananthapur) integrated plants via induction furnace melting and Continuous Casting Machines (CCM). Hariom M.S. Billets feature low inclusion levels, uniform cross-section, and tight chemical composition.',
    applications: ['TMT Re-Rolling Mills', 'Structural Angle & Channel Rolling', 'Wire Rod Plants', 'Forging Industry'],
    specifications: [
      { name: 'Cross Section Sizes', value: '100x100mm, 125x125mm, 130x130mm, 150x150mm' },
      { name: 'Billet Length', value: '6 Meters / 12 Meters (Cut to length)' },
      { name: 'Carbon Content', value: 'IS 2830 / IS 1786 Standard Grades' },
      { name: 'Casting Method', value: 'Curved Mold Continuous Casting Machine (CCM)' },
    ],
    availableSizes: ['100sq, 125sq, 130sq, 150sq x 6m/12m'],
    standards: ['IS 2830', 'IS 1786 Grade Fe415/Fe500'],
    finishes: ['Raw Cast Billet Finish'],
    images: ['/images/products/ms-billets.webp'],
    featured: true,
    isPublished: true,
    viewsCount: 1940,
    createdAt: '2026-01-12T00:00:00.000Z',
    updatedAt: '2026-03-11T00:00:00.000Z',
  },
];

export const SUB_BRANDS = [
  { name: 'Hariom Veer', category: 'Pipes & Tubes', highlight: 'Heavy HR Structural Steel' },
  { name: 'Dura Edge', category: 'Precision CR Pipes & Coils', highlight: 'High Surface Finish & Tolerance' },
  { name: 'Zincon', category: 'GI Pipes & Galvanized Coils', highlight: '360+ g/m² Hot Dipped Zinc Shield' },
  { name: 'Build Master', category: 'Scaffolding Systems', highlight: 'Cuplock & Telescopic Shuttering' },
  { name: '360 Prime', category: 'Premium Coils & Strips', highlight: 'Precision Pickled & Slit Coils' },
];

export const CLIENT_LOGOS = [
  { name: 'Midhani', sector: 'Defense & Metallurgy' },
  { name: 'Pennar Industries', sector: 'Pre-Engineered Buildings' },
  { name: 'Shankara Buildpro', sector: 'Building Material Retail' },
  { name: 'Aparna Constructions', sector: 'Real Estate & Infrastructure' },
  { name: 'Kirby Building Systems', sector: 'Industrial PEB Solutions' },
];

export const CERTIFICATIONS = [
  { code: 'IS 1239 (Part 1)', title: 'Steel Tubes, Tubulars & Other Wrought Steel Fittings' },
  { code: 'IS 1161', title: 'Steel Tubes for Structural Purposes' },
  { code: 'IS 4923', title: 'Hollow Steel Sections for Structural Use (SHS & RHS)' },
  { code: 'IS 4736', title: 'Hot-Dip Zinc Coatings on Mild Steel Tubes' },
  { code: 'ISO 9001:2015', title: 'Quality Management System Standard' },
];
